# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import cipher_pb2 as cipher__pb2


class CipherServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EncryptCaesar = channel.unary_unary(
                '/cipher.CipherService/EncryptCaesar',
                request_serializer=cipher__pb2.CaesarRequest.SerializeToString,
                response_deserializer=cipher__pb2.CipherResponse.FromString,
                _registered_method=True)
        self.DecryptCaesar = channel.unary_unary(
                '/cipher.CipherService/DecryptCaesar',
                request_serializer=cipher__pb2.CaesarRequest.SerializeToString,
                response_deserializer=cipher__pb2.CipherResponse.FromString,
                _registered_method=True)
        self.EncryptColumnar = channel.unary_unary(
                '/cipher.CipherService/EncryptColumnar',
                request_serializer=cipher__pb2.ColumnarRequest.SerializeToString,
                response_deserializer=cipher__pb2.CipherResponse.FromString,
                _registered_method=True)
        self.DecryptColumnar = channel.unary_unary(
                '/cipher.CipherService/DecryptColumnar',
                request_serializer=cipher__pb2.ColumnarRequest.SerializeToString,
                response_deserializer=cipher__pb2.CipherResponse.FromString,
                _registered_method=True)


class CipherServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EncryptCaesar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DecryptCaesar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EncryptColumnar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DecryptColumnar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CipherServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EncryptCaesar': grpc.unary_unary_rpc_method_handler(
                    servicer.EncryptCaesar,
                    request_deserializer=cipher__pb2.CaesarRequest.FromString,
                    response_serializer=cipher__pb2.CipherResponse.SerializeToString,
            ),
            'DecryptCaesar': grpc.unary_unary_rpc_method_handler(
                    servicer.DecryptCaesar,
                    request_deserializer=cipher__pb2.CaesarRequest.FromString,
                    response_serializer=cipher__pb2.CipherResponse.SerializeToString,
            ),
            'EncryptColumnar': grpc.unary_unary_rpc_method_handler(
                    servicer.EncryptColumnar,
                    request_deserializer=cipher__pb2.ColumnarRequest.FromString,
                    response_serializer=cipher__pb2.CipherResponse.SerializeToString,
            ),
            'DecryptColumnar': grpc.unary_unary_rpc_method_handler(
                    servicer.DecryptColumnar,
                    request_deserializer=cipher__pb2.ColumnarRequest.FromString,
                    response_serializer=cipher__pb2.CipherResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cipher.CipherService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cipher.CipherService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CipherService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EncryptCaesar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cipher.CipherService/EncryptCaesar',
            cipher__pb2.CaesarRequest.SerializeToString,
            cipher__pb2.CipherResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DecryptCaesar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cipher.CipherService/DecryptCaesar',
            cipher__pb2.CaesarRequest.SerializeToString,
            cipher__pb2.CipherResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EncryptColumnar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cipher.CipherService/EncryptColumnar',
            cipher__pb2.ColumnarRequest.SerializeToString,
            cipher__pb2.CipherResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DecryptColumnar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cipher.CipherService/DecryptColumnar',
            cipher__pb2.ColumnarRequest.SerializeToString,
            cipher__pb2.CipherResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
