# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cipher.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'cipher.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ipher.proto\x12\x06\x63ipher\",\n\rCaesarRequest\x12\x0c\n\x04text\x18\x01 \x01(\x0c\x12\r\n\x05shift\x18\x02 \x01(\x05\"0\n\x0f\x43olumnarRequest\x12\x0c\n\x04text\x18\x01 \x01(\x0c\x12\x0f\n\x07\x63olumns\x18\x02 \x01(\x05\" \n\x0e\x43ipherResponse\x12\x0e\n\x06result\x18\x01 \x01(\x0c\x32\x97\x02\n\rCipherService\x12>\n\rEncryptCaesar\x12\x15.cipher.CaesarRequest\x1a\x16.cipher.CipherResponse\x12>\n\rDecryptCaesar\x12\x15.cipher.CaesarRequest\x1a\x16.cipher.CipherResponse\x12\x42\n\x0f\x45ncryptColumnar\x12\x17.cipher.ColumnarRequest\x1a\x16.cipher.CipherResponse\x12\x42\n\x0f\x44\x65\x63ryptColumnar\x12\x17.cipher.ColumnarRequest\x1a\x16.cipher.CipherResponseBEZCgithub.com/basarardabaykal/cipherconverter-microservice/internal/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cipher_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZCgithub.com/basarardabaykal/cipherconverter-microservice/internal/pb'
  _globals['_CAESARREQUEST']._serialized_start=24
  _globals['_CAESARREQUEST']._serialized_end=68
  _globals['_COLUMNARREQUEST']._serialized_start=70
  _globals['_COLUMNARREQUEST']._serialized_end=118
  _globals['_CIPHERRESPONSE']._serialized_start=120
  _globals['_CIPHERRESPONSE']._serialized_end=152
  _globals['_CIPHERSERVICE']._serialized_start=155
  _globals['_CIPHERSERVICE']._serialized_end=434
# @@protoc_insertion_point(module_scope)
