# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import common_pb2 as common__pb2
from . import symmetric_pb2 as symmetric__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in symmetric_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CipherServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EncryptCaesar = channel.unary_unary(
                '/symmetric.CipherService/EncryptCaesar',
                request_serializer=symmetric__pb2.CaesarRequest.SerializeToString,
                response_deserializer=common__pb2.CipherResponse.FromString,
                _registered_method=True)
        self.DecryptCaesar = channel.unary_unary(
                '/symmetric.CipherService/DecryptCaesar',
                request_serializer=symmetric__pb2.CaesarRequest.SerializeToString,
                response_deserializer=common__pb2.CipherResponse.FromString,
                _registered_method=True)
        self.EncryptColumnar = channel.unary_unary(
                '/symmetric.CipherService/EncryptColumnar',
                request_serializer=symmetric__pb2.ColumnarRequest.SerializeToString,
                response_deserializer=common__pb2.CipherResponse.FromString,
                _registered_method=True)
        self.DecryptColumnar = channel.unary_unary(
                '/symmetric.CipherService/DecryptColumnar',
                request_serializer=symmetric__pb2.ColumnarRequest.SerializeToString,
                response_deserializer=common__pb2.CipherResponse.FromString,
                _registered_method=True)
        self.EncryptOTP = channel.unary_unary(
                '/symmetric.CipherService/EncryptOTP',
                request_serializer=symmetric__pb2.OTPRequest.SerializeToString,
                response_deserializer=common__pb2.CipherResponse.FromString,
                _registered_method=True)
        self.DecryptOTP = channel.unary_unary(
                '/symmetric.CipherService/DecryptOTP',
                request_serializer=symmetric__pb2.OTPRequest.SerializeToString,
                response_deserializer=common__pb2.CipherResponse.FromString,
                _registered_method=True)


class CipherServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EncryptCaesar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DecryptCaesar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EncryptColumnar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DecryptColumnar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EncryptOTP(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DecryptOTP(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CipherServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EncryptCaesar': grpc.unary_unary_rpc_method_handler(
                    servicer.EncryptCaesar,
                    request_deserializer=symmetric__pb2.CaesarRequest.FromString,
                    response_serializer=common__pb2.CipherResponse.SerializeToString,
            ),
            'DecryptCaesar': grpc.unary_unary_rpc_method_handler(
                    servicer.DecryptCaesar,
                    request_deserializer=symmetric__pb2.CaesarRequest.FromString,
                    response_serializer=common__pb2.CipherResponse.SerializeToString,
            ),
            'EncryptColumnar': grpc.unary_unary_rpc_method_handler(
                    servicer.EncryptColumnar,
                    request_deserializer=symmetric__pb2.ColumnarRequest.FromString,
                    response_serializer=common__pb2.CipherResponse.SerializeToString,
            ),
            'DecryptColumnar': grpc.unary_unary_rpc_method_handler(
                    servicer.DecryptColumnar,
                    request_deserializer=symmetric__pb2.ColumnarRequest.FromString,
                    response_serializer=common__pb2.CipherResponse.SerializeToString,
            ),
            'EncryptOTP': grpc.unary_unary_rpc_method_handler(
                    servicer.EncryptOTP,
                    request_deserializer=symmetric__pb2.OTPRequest.FromString,
                    response_serializer=common__pb2.CipherResponse.SerializeToString,
            ),
            'DecryptOTP': grpc.unary_unary_rpc_method_handler(
                    servicer.DecryptOTP,
                    request_deserializer=symmetric__pb2.OTPRequest.FromString,
                    response_serializer=common__pb2.CipherResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'symmetric.CipherService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('symmetric.CipherService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CipherService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EncryptCaesar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/symmetric.CipherService/EncryptCaesar',
            symmetric__pb2.CaesarRequest.SerializeToString,
            common__pb2.CipherResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DecryptCaesar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/symmetric.CipherService/DecryptCaesar',
            symmetric__pb2.CaesarRequest.SerializeToString,
            common__pb2.CipherResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EncryptColumnar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/symmetric.CipherService/EncryptColumnar',
            symmetric__pb2.ColumnarRequest.SerializeToString,
            common__pb2.CipherResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DecryptColumnar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/symmetric.CipherService/DecryptColumnar',
            symmetric__pb2.ColumnarRequest.SerializeToString,
            common__pb2.CipherResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EncryptOTP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/symmetric.CipherService/EncryptOTP',
            symmetric__pb2.OTPRequest.SerializeToString,
            common__pb2.CipherResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DecryptOTP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/symmetric.CipherService/DecryptOTP',
            symmetric__pb2.OTPRequest.SerializeToString,
            common__pb2.CipherResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
