# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: symmetric.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'symmetric.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fsymmetric.proto\x12\tsymmetric\x1a\x0c\x63ommon.proto\",\n\rCaesarRequest\x12\x0c\n\x04text\x18\x01 \x01(\x0c\x12\r\n\x05shift\x18\x02 \x01(\x05\"0\n\x0f\x43olumnarRequest\x12\x0c\n\x04text\x18\x01 \x01(\x0c\x12\x0f\n\x07\x63olumns\x18\x02 \x01(\x05\"\'\n\nOTPRequest\x12\x0c\n\x04text\x18\x01 \x01(\x0c\x12\x0b\n\x03key\x18\x02 \x01(\x0c\"3\n\rAffineRequest\x12\x0c\n\x04text\x18\x01 \x01(\x0c\x12\t\n\x01\x61\x18\x02 \x01(\x05\x12\t\n\x01\x62\x18\x03 \x01(\x05\x32\x9d\x03\n\rCipherService\x12\x41\n\rEncryptCaesar\x12\x18.symmetric.CaesarRequest\x1a\x16.common.CipherResponse\x12\x41\n\rDecryptCaesar\x12\x18.symmetric.CaesarRequest\x1a\x16.common.CipherResponse\x12\x45\n\x0f\x45ncryptColumnar\x12\x1a.symmetric.ColumnarRequest\x1a\x16.common.CipherResponse\x12\x45\n\x0f\x44\x65\x63ryptColumnar\x12\x1a.symmetric.ColumnarRequest\x1a\x16.common.CipherResponse\x12;\n\nEncryptOTP\x12\x15.symmetric.OTPRequest\x1a\x16.common.CipherResponse\x12;\n\nDecryptOTP\x12\x15.symmetric.OTPRequest\x1a\x16.common.CipherResponseBOZMgithub.com/basarardabaykal/cipherconverter-microservice/internal/pb/symmetricb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'symmetric_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZMgithub.com/basarardabaykal/cipherconverter-microservice/internal/pb/symmetric'
  _globals['_CAESARREQUEST']._serialized_start=44
  _globals['_CAESARREQUEST']._serialized_end=88
  _globals['_COLUMNARREQUEST']._serialized_start=90
  _globals['_COLUMNARREQUEST']._serialized_end=138
  _globals['_OTPREQUEST']._serialized_start=140
  _globals['_OTPREQUEST']._serialized_end=179
  _globals['_AFFINEREQUEST']._serialized_start=181
  _globals['_AFFINEREQUEST']._serialized_end=232
  _globals['_CIPHERSERVICE']._serialized_start=235
  _globals['_CIPHERSERVICE']._serialized_end=648
# @@protoc_insertion_point(module_scope)
