# Generated by Django 5.2.11 on 2026-04-01 19:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Affine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('input_text', models.TextField()),
                ('output_text', models.TextField()),
                ('operation', models.CharField(choices=[('encrypt', 'Encrypt'), ('decrypt', 'Decrypt')], db_index=True, max_length=10)),
                ('a', models.IntegerField(choices=[(1, '1'), (3, '3'), (5, '5'), (7, '7'), (9, '9'), (11, '11'), (15, '15'), (17, '17'), (19, '19'), (21, '21'), (23, '23'), (25, '25')])),
                ('b', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)])),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Caesar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('input_text', models.TextField()),
                ('output_text', models.TextField()),
                ('operation', models.CharField(choices=[('encrypt', 'Encrypt'), ('decrypt', 'Decrypt')], db_index=True, max_length=10)),
                ('key', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(26)])),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
